# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from actuatorcontroller_ros/AttributeDictionaryRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class AttributeDictionaryRequest(genpy.Message):
  _md5sum = "09d7751ad75650052cbe9c05d56210ee"
  _type = "actuatorcontroller_ros/AttributeDictionaryRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """std_msgs/String LookupTerm

================================================================================
MSG: std_msgs/String
string data
"""
  __slots__ = ['LookupTerm']
  _slot_types = ['std_msgs/String']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       LookupTerm

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AttributeDictionaryRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.LookupTerm is None:
        self.LookupTerm = std_msgs.msg.String()
    else:
      self.LookupTerm = std_msgs.msg.String()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.LookupTerm.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.LookupTerm is None:
        self.LookupTerm = std_msgs.msg.String()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.LookupTerm.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.LookupTerm.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.LookupTerm.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.LookupTerm is None:
        self.LookupTerm = std_msgs.msg.String()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.LookupTerm.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.LookupTerm.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from actuatorcontroller_ros/AttributeDictionaryResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class AttributeDictionaryResponse(genpy.Message):
  _md5sum = "4f13c300070b2510fed8b3db79117cab"
  _type = "actuatorcontroller_ros/AttributeDictionaryResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """std_msgs/String TermType
bool isChangeable
std_msgs/String TermExplanation


================================================================================
MSG: std_msgs/String
string data
"""
  __slots__ = ['TermType','isChangeable','TermExplanation']
  _slot_types = ['std_msgs/String','bool','std_msgs/String']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       TermType,isChangeable,TermExplanation

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AttributeDictionaryResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.TermType is None:
        self.TermType = std_msgs.msg.String()
      if self.isChangeable is None:
        self.isChangeable = False
      if self.TermExplanation is None:
        self.TermExplanation = std_msgs.msg.String()
    else:
      self.TermType = std_msgs.msg.String()
      self.isChangeable = False
      self.TermExplanation = std_msgs.msg.String()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.TermType.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.isChangeable
      buff.write(_get_struct_B().pack(_x))
      _x = self.TermExplanation.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.TermType is None:
        self.TermType = std_msgs.msg.String()
      if self.TermExplanation is None:
        self.TermExplanation = std_msgs.msg.String()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.TermType.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.TermType.data = str[start:end]
      start = end
      end += 1
      (self.isChangeable,) = _get_struct_B().unpack(str[start:end])
      self.isChangeable = bool(self.isChangeable)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.TermExplanation.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.TermExplanation.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.TermType.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.isChangeable
      buff.write(_get_struct_B().pack(_x))
      _x = self.TermExplanation.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.TermType is None:
        self.TermType = std_msgs.msg.String()
      if self.TermExplanation is None:
        self.TermExplanation = std_msgs.msg.String()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.TermType.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.TermType.data = str[start:end]
      start = end
      end += 1
      (self.isChangeable,) = _get_struct_B().unpack(str[start:end])
      self.isChangeable = bool(self.isChangeable)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.TermExplanation.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.TermExplanation.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
class AttributeDictionary(object):
  _type          = 'actuatorcontroller_ros/AttributeDictionary'
  _md5sum = '86cb20b614a056db93aedc2debacabe6'
  _request_class  = AttributeDictionaryRequest
  _response_class = AttributeDictionaryResponse
