// Generated by gencpp from file unity_robotics_demo_msgs/gluoncontrol.msg
// DO NOT EDIT!


#ifndef UNITY_ROBOTICS_DEMO_MSGS_MESSAGE_GLUONCONTROL_H
#define UNITY_ROBOTICS_DEMO_MSGS_MESSAGE_GLUONCONTROL_H

#include <ros/service_traits.h>


#include <unity_robotics_demo_msgs/gluoncontrolRequest.h>
#include <unity_robotics_demo_msgs/gluoncontrolResponse.h>


namespace unity_robotics_demo_msgs
{

struct gluoncontrol
{

typedef gluoncontrolRequest Request;
typedef gluoncontrolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct gluoncontrol
} // namespace unity_robotics_demo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::unity_robotics_demo_msgs::gluoncontrol > {
  static const char* value()
  {
    return "c22403d57765af34cae9f82482d11146";
  }

  static const char* value(const ::unity_robotics_demo_msgs::gluoncontrol&) { return value(); }
};

template<>
struct DataType< ::unity_robotics_demo_msgs::gluoncontrol > {
  static const char* value()
  {
    return "unity_robotics_demo_msgs/gluoncontrol";
  }

  static const char* value(const ::unity_robotics_demo_msgs::gluoncontrol&) { return value(); }
};


// service_traits::MD5Sum< ::unity_robotics_demo_msgs::gluoncontrolRequest> should match
// service_traits::MD5Sum< ::unity_robotics_demo_msgs::gluoncontrol >
template<>
struct MD5Sum< ::unity_robotics_demo_msgs::gluoncontrolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::unity_robotics_demo_msgs::gluoncontrol >::value();
  }
  static const char* value(const ::unity_robotics_demo_msgs::gluoncontrolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::unity_robotics_demo_msgs::gluoncontrolRequest> should match
// service_traits::DataType< ::unity_robotics_demo_msgs::gluoncontrol >
template<>
struct DataType< ::unity_robotics_demo_msgs::gluoncontrolRequest>
{
  static const char* value()
  {
    return DataType< ::unity_robotics_demo_msgs::gluoncontrol >::value();
  }
  static const char* value(const ::unity_robotics_demo_msgs::gluoncontrolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::unity_robotics_demo_msgs::gluoncontrolResponse> should match
// service_traits::MD5Sum< ::unity_robotics_demo_msgs::gluoncontrol >
template<>
struct MD5Sum< ::unity_robotics_demo_msgs::gluoncontrolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::unity_robotics_demo_msgs::gluoncontrol >::value();
  }
  static const char* value(const ::unity_robotics_demo_msgs::gluoncontrolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::unity_robotics_demo_msgs::gluoncontrolResponse> should match
// service_traits::DataType< ::unity_robotics_demo_msgs::gluoncontrol >
template<>
struct DataType< ::unity_robotics_demo_msgs::gluoncontrolResponse>
{
  static const char* value()
  {
    return DataType< ::unity_robotics_demo_msgs::gluoncontrol >::value();
  }
  static const char* value(const ::unity_robotics_demo_msgs::gluoncontrolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UNITY_ROBOTICS_DEMO_MSGS_MESSAGE_GLUONCONTROL_H
