// Generated by gencpp from file actuatorcontroller_ros/ActuatorAttribute.msg
// DO NOT EDIT!


#ifndef ACTUATORCONTROLLER_ROS_MESSAGE_ACTUATORATTRIBUTE_H
#define ACTUATORCONTROLLER_ROS_MESSAGE_ACTUATORATTRIBUTE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace actuatorcontroller_ros
{
template <class ContainerAllocator>
struct ActuatorAttribute_
{
  typedef ActuatorAttribute_<ContainerAllocator> Type;

  ActuatorAttribute_()
    : JointID(0)
    , AttributeID(0)
    , Value(0.0)  {
    }
  ActuatorAttribute_(const ContainerAllocator& _alloc)
    : JointID(0)
    , AttributeID(0)
    , Value(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _JointID_type;
  _JointID_type JointID;

   typedef int32_t _AttributeID_type;
  _AttributeID_type AttributeID;

   typedef double _Value_type;
  _Value_type Value;





  typedef boost::shared_ptr< ::actuatorcontroller_ros::ActuatorAttribute_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::actuatorcontroller_ros::ActuatorAttribute_<ContainerAllocator> const> ConstPtr;

}; // struct ActuatorAttribute_

typedef ::actuatorcontroller_ros::ActuatorAttribute_<std::allocator<void> > ActuatorAttribute;

typedef boost::shared_ptr< ::actuatorcontroller_ros::ActuatorAttribute > ActuatorAttributePtr;
typedef boost::shared_ptr< ::actuatorcontroller_ros::ActuatorAttribute const> ActuatorAttributeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::actuatorcontroller_ros::ActuatorAttribute_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::actuatorcontroller_ros::ActuatorAttribute_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::actuatorcontroller_ros::ActuatorAttribute_<ContainerAllocator1> & lhs, const ::actuatorcontroller_ros::ActuatorAttribute_<ContainerAllocator2> & rhs)
{
  return lhs.JointID == rhs.JointID &&
    lhs.AttributeID == rhs.AttributeID &&
    lhs.Value == rhs.Value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::actuatorcontroller_ros::ActuatorAttribute_<ContainerAllocator1> & lhs, const ::actuatorcontroller_ros::ActuatorAttribute_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace actuatorcontroller_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::actuatorcontroller_ros::ActuatorAttribute_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actuatorcontroller_ros::ActuatorAttribute_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actuatorcontroller_ros::ActuatorAttribute_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actuatorcontroller_ros::ActuatorAttribute_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actuatorcontroller_ros::ActuatorAttribute_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actuatorcontroller_ros::ActuatorAttribute_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::actuatorcontroller_ros::ActuatorAttribute_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25e4b029e7f8b477579e0dbe72634840";
  }

  static const char* value(const ::actuatorcontroller_ros::ActuatorAttribute_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25e4b029e7f8b477ULL;
  static const uint64_t static_value2 = 0x579e0dbe72634840ULL;
};

template<class ContainerAllocator>
struct DataType< ::actuatorcontroller_ros::ActuatorAttribute_<ContainerAllocator> >
{
  static const char* value()
  {
    return "actuatorcontroller_ros/ActuatorAttribute";
  }

  static const char* value(const ::actuatorcontroller_ros::ActuatorAttribute_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::actuatorcontroller_ros::ActuatorAttribute_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 JointID\n"
"int32 AttributeID\n"
"float64 Value\n"
;
  }

  static const char* value(const ::actuatorcontroller_ros::ActuatorAttribute_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::actuatorcontroller_ros::ActuatorAttribute_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.JointID);
      stream.next(m.AttributeID);
      stream.next(m.Value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActuatorAttribute_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::actuatorcontroller_ros::ActuatorAttribute_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::actuatorcontroller_ros::ActuatorAttribute_<ContainerAllocator>& v)
  {
    s << indent << "JointID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.JointID);
    s << indent << "AttributeID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.AttributeID);
    s << indent << "Value: ";
    Printer<double>::stream(s, indent + "  ", v.Value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTUATORCONTROLLER_ROS_MESSAGE_ACTUATORATTRIBUTE_H
