// Generated by gencpp from file actuatorcontroller_ros/DebugQuery.msg
// DO NOT EDIT!


#ifndef ACTUATORCONTROLLER_ROS_MESSAGE_DEBUGQUERY_H
#define ACTUATORCONTROLLER_ROS_MESSAGE_DEBUGQUERY_H

#include <ros/service_traits.h>


#include <actuatorcontroller_ros/DebugQueryRequest.h>
#include <actuatorcontroller_ros/DebugQueryResponse.h>


namespace actuatorcontroller_ros
{

struct DebugQuery
{

typedef DebugQueryRequest Request;
typedef DebugQueryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DebugQuery
} // namespace actuatorcontroller_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::actuatorcontroller_ros::DebugQuery > {
  static const char* value()
  {
    return "b3134f9c6ee76fc9a23efe69e05775ac";
  }

  static const char* value(const ::actuatorcontroller_ros::DebugQuery&) { return value(); }
};

template<>
struct DataType< ::actuatorcontroller_ros::DebugQuery > {
  static const char* value()
  {
    return "actuatorcontroller_ros/DebugQuery";
  }

  static const char* value(const ::actuatorcontroller_ros::DebugQuery&) { return value(); }
};


// service_traits::MD5Sum< ::actuatorcontroller_ros::DebugQueryRequest> should match
// service_traits::MD5Sum< ::actuatorcontroller_ros::DebugQuery >
template<>
struct MD5Sum< ::actuatorcontroller_ros::DebugQueryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::actuatorcontroller_ros::DebugQuery >::value();
  }
  static const char* value(const ::actuatorcontroller_ros::DebugQueryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::actuatorcontroller_ros::DebugQueryRequest> should match
// service_traits::DataType< ::actuatorcontroller_ros::DebugQuery >
template<>
struct DataType< ::actuatorcontroller_ros::DebugQueryRequest>
{
  static const char* value()
  {
    return DataType< ::actuatorcontroller_ros::DebugQuery >::value();
  }
  static const char* value(const ::actuatorcontroller_ros::DebugQueryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::actuatorcontroller_ros::DebugQueryResponse> should match
// service_traits::MD5Sum< ::actuatorcontroller_ros::DebugQuery >
template<>
struct MD5Sum< ::actuatorcontroller_ros::DebugQueryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::actuatorcontroller_ros::DebugQuery >::value();
  }
  static const char* value(const ::actuatorcontroller_ros::DebugQueryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::actuatorcontroller_ros::DebugQueryResponse> should match
// service_traits::DataType< ::actuatorcontroller_ros::DebugQuery >
template<>
struct DataType< ::actuatorcontroller_ros::DebugQueryResponse>
{
  static const char* value()
  {
    return DataType< ::actuatorcontroller_ros::DebugQuery >::value();
  }
  static const char* value(const ::actuatorcontroller_ros::DebugQueryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ACTUATORCONTROLLER_ROS_MESSAGE_DEBUGQUERY_H
