// Generated by gencpp from file actuatorcontroller_ros/GeneralQuery.msg
// DO NOT EDIT!


#ifndef ACTUATORCONTROLLER_ROS_MESSAGE_GENERALQUERY_H
#define ACTUATORCONTROLLER_ROS_MESSAGE_GENERALQUERY_H

#include <ros/service_traits.h>


#include <actuatorcontroller_ros/GeneralQueryRequest.h>
#include <actuatorcontroller_ros/GeneralQueryResponse.h>


namespace actuatorcontroller_ros
{

struct GeneralQuery
{

typedef GeneralQueryRequest Request;
typedef GeneralQueryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GeneralQuery
} // namespace actuatorcontroller_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::actuatorcontroller_ros::GeneralQuery > {
  static const char* value()
  {
    return "36481795cc1cc8f6a7e6a2ef71e4eeb0";
  }

  static const char* value(const ::actuatorcontroller_ros::GeneralQuery&) { return value(); }
};

template<>
struct DataType< ::actuatorcontroller_ros::GeneralQuery > {
  static const char* value()
  {
    return "actuatorcontroller_ros/GeneralQuery";
  }

  static const char* value(const ::actuatorcontroller_ros::GeneralQuery&) { return value(); }
};


// service_traits::MD5Sum< ::actuatorcontroller_ros::GeneralQueryRequest> should match
// service_traits::MD5Sum< ::actuatorcontroller_ros::GeneralQuery >
template<>
struct MD5Sum< ::actuatorcontroller_ros::GeneralQueryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::actuatorcontroller_ros::GeneralQuery >::value();
  }
  static const char* value(const ::actuatorcontroller_ros::GeneralQueryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::actuatorcontroller_ros::GeneralQueryRequest> should match
// service_traits::DataType< ::actuatorcontroller_ros::GeneralQuery >
template<>
struct DataType< ::actuatorcontroller_ros::GeneralQueryRequest>
{
  static const char* value()
  {
    return DataType< ::actuatorcontroller_ros::GeneralQuery >::value();
  }
  static const char* value(const ::actuatorcontroller_ros::GeneralQueryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::actuatorcontroller_ros::GeneralQueryResponse> should match
// service_traits::MD5Sum< ::actuatorcontroller_ros::GeneralQuery >
template<>
struct MD5Sum< ::actuatorcontroller_ros::GeneralQueryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::actuatorcontroller_ros::GeneralQuery >::value();
  }
  static const char* value(const ::actuatorcontroller_ros::GeneralQueryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::actuatorcontroller_ros::GeneralQueryResponse> should match
// service_traits::DataType< ::actuatorcontroller_ros::GeneralQuery >
template<>
struct DataType< ::actuatorcontroller_ros::GeneralQueryResponse>
{
  static const char* value()
  {
    return DataType< ::actuatorcontroller_ros::GeneralQuery >::value();
  }
  static const char* value(const ::actuatorcontroller_ros::GeneralQueryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ACTUATORCONTROLLER_ROS_MESSAGE_GENERALQUERY_H
