// Generated by gencpp from file actuatorcontroller_ros/IDModifyRequest.msg
// DO NOT EDIT!


#ifndef ACTUATORCONTROLLER_ROS_MESSAGE_IDMODIFYREQUEST_H
#define ACTUATORCONTROLLER_ROS_MESSAGE_IDMODIFYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace actuatorcontroller_ros
{
template <class ContainerAllocator>
struct IDModifyRequest_
{
  typedef IDModifyRequest_<ContainerAllocator> Type;

  IDModifyRequest_()
    : OriginalJointID(0)
    , ModifiedJointID(0)  {
    }
  IDModifyRequest_(const ContainerAllocator& _alloc)
    : OriginalJointID(0)
    , ModifiedJointID(0)  {
  (void)_alloc;
    }



   typedef int32_t _OriginalJointID_type;
  _OriginalJointID_type OriginalJointID;

   typedef int32_t _ModifiedJointID_type;
  _ModifiedJointID_type ModifiedJointID;





  typedef boost::shared_ptr< ::actuatorcontroller_ros::IDModifyRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::actuatorcontroller_ros::IDModifyRequest_<ContainerAllocator> const> ConstPtr;

}; // struct IDModifyRequest_

typedef ::actuatorcontroller_ros::IDModifyRequest_<std::allocator<void> > IDModifyRequest;

typedef boost::shared_ptr< ::actuatorcontroller_ros::IDModifyRequest > IDModifyRequestPtr;
typedef boost::shared_ptr< ::actuatorcontroller_ros::IDModifyRequest const> IDModifyRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::actuatorcontroller_ros::IDModifyRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::actuatorcontroller_ros::IDModifyRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::actuatorcontroller_ros::IDModifyRequest_<ContainerAllocator1> & lhs, const ::actuatorcontroller_ros::IDModifyRequest_<ContainerAllocator2> & rhs)
{
  return lhs.OriginalJointID == rhs.OriginalJointID &&
    lhs.ModifiedJointID == rhs.ModifiedJointID;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::actuatorcontroller_ros::IDModifyRequest_<ContainerAllocator1> & lhs, const ::actuatorcontroller_ros::IDModifyRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace actuatorcontroller_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::actuatorcontroller_ros::IDModifyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actuatorcontroller_ros::IDModifyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actuatorcontroller_ros::IDModifyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actuatorcontroller_ros::IDModifyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actuatorcontroller_ros::IDModifyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actuatorcontroller_ros::IDModifyRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::actuatorcontroller_ros::IDModifyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af12b9d997c464572bc3019e0d147816";
  }

  static const char* value(const ::actuatorcontroller_ros::IDModifyRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf12b9d997c46457ULL;
  static const uint64_t static_value2 = 0x2bc3019e0d147816ULL;
};

template<class ContainerAllocator>
struct DataType< ::actuatorcontroller_ros::IDModifyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "actuatorcontroller_ros/IDModifyRequest";
  }

  static const char* value(const ::actuatorcontroller_ros::IDModifyRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::actuatorcontroller_ros::IDModifyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 OriginalJointID\n"
"int32 ModifiedJointID\n"
;
  }

  static const char* value(const ::actuatorcontroller_ros::IDModifyRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::actuatorcontroller_ros::IDModifyRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.OriginalJointID);
      stream.next(m.ModifiedJointID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IDModifyRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::actuatorcontroller_ros::IDModifyRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::actuatorcontroller_ros::IDModifyRequest_<ContainerAllocator>& v)
  {
    s << indent << "OriginalJointID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.OriginalJointID);
    s << indent << "ModifiedJointID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ModifiedJointID);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTUATORCONTROLLER_ROS_MESSAGE_IDMODIFYREQUEST_H
