// Generated by gencpp from file actuatorcontroller_ros/ParametersSave.msg
// DO NOT EDIT!


#ifndef ACTUATORCONTROLLER_ROS_MESSAGE_PARAMETERSSAVE_H
#define ACTUATORCONTROLLER_ROS_MESSAGE_PARAMETERSSAVE_H

#include <ros/service_traits.h>


#include <actuatorcontroller_ros/ParametersSaveRequest.h>
#include <actuatorcontroller_ros/ParametersSaveResponse.h>


namespace actuatorcontroller_ros
{

struct ParametersSave
{

typedef ParametersSaveRequest Request;
typedef ParametersSaveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ParametersSave
} // namespace actuatorcontroller_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::actuatorcontroller_ros::ParametersSave > {
  static const char* value()
  {
    return "0d3668e75a83f1a2c384dc3303946576";
  }

  static const char* value(const ::actuatorcontroller_ros::ParametersSave&) { return value(); }
};

template<>
struct DataType< ::actuatorcontroller_ros::ParametersSave > {
  static const char* value()
  {
    return "actuatorcontroller_ros/ParametersSave";
  }

  static const char* value(const ::actuatorcontroller_ros::ParametersSave&) { return value(); }
};


// service_traits::MD5Sum< ::actuatorcontroller_ros::ParametersSaveRequest> should match
// service_traits::MD5Sum< ::actuatorcontroller_ros::ParametersSave >
template<>
struct MD5Sum< ::actuatorcontroller_ros::ParametersSaveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::actuatorcontroller_ros::ParametersSave >::value();
  }
  static const char* value(const ::actuatorcontroller_ros::ParametersSaveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::actuatorcontroller_ros::ParametersSaveRequest> should match
// service_traits::DataType< ::actuatorcontroller_ros::ParametersSave >
template<>
struct DataType< ::actuatorcontroller_ros::ParametersSaveRequest>
{
  static const char* value()
  {
    return DataType< ::actuatorcontroller_ros::ParametersSave >::value();
  }
  static const char* value(const ::actuatorcontroller_ros::ParametersSaveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::actuatorcontroller_ros::ParametersSaveResponse> should match
// service_traits::MD5Sum< ::actuatorcontroller_ros::ParametersSave >
template<>
struct MD5Sum< ::actuatorcontroller_ros::ParametersSaveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::actuatorcontroller_ros::ParametersSave >::value();
  }
  static const char* value(const ::actuatorcontroller_ros::ParametersSaveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::actuatorcontroller_ros::ParametersSaveResponse> should match
// service_traits::DataType< ::actuatorcontroller_ros::ParametersSave >
template<>
struct DataType< ::actuatorcontroller_ros::ParametersSaveResponse>
{
  static const char* value()
  {
    return DataType< ::actuatorcontroller_ros::ParametersSave >::value();
  }
  static const char* value(const ::actuatorcontroller_ros::ParametersSaveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ACTUATORCONTROLLER_ROS_MESSAGE_PARAMETERSSAVE_H
