// Generated by gencpp from file actuatorcontroller_ros/ZeroReset.msg
// DO NOT EDIT!


#ifndef ACTUATORCONTROLLER_ROS_MESSAGE_ZERORESET_H
#define ACTUATORCONTROLLER_ROS_MESSAGE_ZERORESET_H

#include <ros/service_traits.h>


#include <actuatorcontroller_ros/ZeroResetRequest.h>
#include <actuatorcontroller_ros/ZeroResetResponse.h>


namespace actuatorcontroller_ros
{

struct ZeroReset
{

typedef ZeroResetRequest Request;
typedef ZeroResetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ZeroReset
} // namespace actuatorcontroller_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::actuatorcontroller_ros::ZeroReset > {
  static const char* value()
  {
    return "f9b0f2e6cbc43ac30a5f971bb8cd2fa9";
  }

  static const char* value(const ::actuatorcontroller_ros::ZeroReset&) { return value(); }
};

template<>
struct DataType< ::actuatorcontroller_ros::ZeroReset > {
  static const char* value()
  {
    return "actuatorcontroller_ros/ZeroReset";
  }

  static const char* value(const ::actuatorcontroller_ros::ZeroReset&) { return value(); }
};


// service_traits::MD5Sum< ::actuatorcontroller_ros::ZeroResetRequest> should match
// service_traits::MD5Sum< ::actuatorcontroller_ros::ZeroReset >
template<>
struct MD5Sum< ::actuatorcontroller_ros::ZeroResetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::actuatorcontroller_ros::ZeroReset >::value();
  }
  static const char* value(const ::actuatorcontroller_ros::ZeroResetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::actuatorcontroller_ros::ZeroResetRequest> should match
// service_traits::DataType< ::actuatorcontroller_ros::ZeroReset >
template<>
struct DataType< ::actuatorcontroller_ros::ZeroResetRequest>
{
  static const char* value()
  {
    return DataType< ::actuatorcontroller_ros::ZeroReset >::value();
  }
  static const char* value(const ::actuatorcontroller_ros::ZeroResetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::actuatorcontroller_ros::ZeroResetResponse> should match
// service_traits::MD5Sum< ::actuatorcontroller_ros::ZeroReset >
template<>
struct MD5Sum< ::actuatorcontroller_ros::ZeroResetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::actuatorcontroller_ros::ZeroReset >::value();
  }
  static const char* value(const ::actuatorcontroller_ros::ZeroResetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::actuatorcontroller_ros::ZeroResetResponse> should match
// service_traits::DataType< ::actuatorcontroller_ros::ZeroReset >
template<>
struct DataType< ::actuatorcontroller_ros::ZeroResetResponse>
{
  static const char* value()
  {
    return DataType< ::actuatorcontroller_ros::ZeroReset >::value();
  }
  static const char* value(const ::actuatorcontroller_ros::ZeroResetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ACTUATORCONTROLLER_ROS_MESSAGE_ZERORESET_H
