// Generated by gencpp from file actuatorcontroller_ros/ActuatorArray.msg
// DO NOT EDIT!


#ifndef ACTUATORCONTROLLER_ROS_MESSAGE_ACTUATORARRAY_H
#define ACTUATORCONTROLLER_ROS_MESSAGE_ACTUATORARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace actuatorcontroller_ros
{
template <class ContainerAllocator>
struct ActuatorArray_
{
  typedef ActuatorArray_<ContainerAllocator> Type;

  ActuatorArray_()
    : JointIDs()  {
    }
  ActuatorArray_(const ContainerAllocator& _alloc)
    : JointIDs(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _JointIDs_type;
  _JointIDs_type JointIDs;





  typedef boost::shared_ptr< ::actuatorcontroller_ros::ActuatorArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::actuatorcontroller_ros::ActuatorArray_<ContainerAllocator> const> ConstPtr;

}; // struct ActuatorArray_

typedef ::actuatorcontroller_ros::ActuatorArray_<std::allocator<void> > ActuatorArray;

typedef boost::shared_ptr< ::actuatorcontroller_ros::ActuatorArray > ActuatorArrayPtr;
typedef boost::shared_ptr< ::actuatorcontroller_ros::ActuatorArray const> ActuatorArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::actuatorcontroller_ros::ActuatorArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::actuatorcontroller_ros::ActuatorArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::actuatorcontroller_ros::ActuatorArray_<ContainerAllocator1> & lhs, const ::actuatorcontroller_ros::ActuatorArray_<ContainerAllocator2> & rhs)
{
  return lhs.JointIDs == rhs.JointIDs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::actuatorcontroller_ros::ActuatorArray_<ContainerAllocator1> & lhs, const ::actuatorcontroller_ros::ActuatorArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace actuatorcontroller_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::actuatorcontroller_ros::ActuatorArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actuatorcontroller_ros::ActuatorArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actuatorcontroller_ros::ActuatorArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actuatorcontroller_ros::ActuatorArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actuatorcontroller_ros::ActuatorArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actuatorcontroller_ros::ActuatorArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::actuatorcontroller_ros::ActuatorArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2149ca671ba16b29e624af1b56e3320e";
  }

  static const char* value(const ::actuatorcontroller_ros::ActuatorArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2149ca671ba16b29ULL;
  static const uint64_t static_value2 = 0xe624af1b56e3320eULL;
};

template<class ContainerAllocator>
struct DataType< ::actuatorcontroller_ros::ActuatorArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "actuatorcontroller_ros/ActuatorArray";
  }

  static const char* value(const ::actuatorcontroller_ros::ActuatorArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::actuatorcontroller_ros::ActuatorArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] JointIDs\n"
;
  }

  static const char* value(const ::actuatorcontroller_ros::ActuatorArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::actuatorcontroller_ros::ActuatorArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.JointIDs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActuatorArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::actuatorcontroller_ros::ActuatorArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::actuatorcontroller_ros::ActuatorArray_<ContainerAllocator>& v)
  {
    s << indent << "JointIDs[]" << std::endl;
    for (size_t i = 0; i < v.JointIDs.size(); ++i)
    {
      s << indent << "  JointIDs[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.JointIDs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTUATORCONTROLLER_ROS_MESSAGE_ACTUATORARRAY_H
