// Generated by gencpp from file actuatorcontroller_ros/ActuatorCommand.msg
// DO NOT EDIT!


#ifndef ACTUATORCONTROLLER_ROS_MESSAGE_ACTUATORCOMMAND_H
#define ACTUATORCONTROLLER_ROS_MESSAGE_ACTUATORCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace actuatorcontroller_ros
{
template <class ContainerAllocator>
struct ActuatorCommand_
{
  typedef ActuatorCommand_<ContainerAllocator> Type;

  ActuatorCommand_()
    : JointID(0)
    , TargetValue(0.0)  {
    }
  ActuatorCommand_(const ContainerAllocator& _alloc)
    : JointID(0)
    , TargetValue(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _JointID_type;
  _JointID_type JointID;

   typedef double _TargetValue_type;
  _TargetValue_type TargetValue;





  typedef boost::shared_ptr< ::actuatorcontroller_ros::ActuatorCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::actuatorcontroller_ros::ActuatorCommand_<ContainerAllocator> const> ConstPtr;

}; // struct ActuatorCommand_

typedef ::actuatorcontroller_ros::ActuatorCommand_<std::allocator<void> > ActuatorCommand;

typedef boost::shared_ptr< ::actuatorcontroller_ros::ActuatorCommand > ActuatorCommandPtr;
typedef boost::shared_ptr< ::actuatorcontroller_ros::ActuatorCommand const> ActuatorCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::actuatorcontroller_ros::ActuatorCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::actuatorcontroller_ros::ActuatorCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::actuatorcontroller_ros::ActuatorCommand_<ContainerAllocator1> & lhs, const ::actuatorcontroller_ros::ActuatorCommand_<ContainerAllocator2> & rhs)
{
  return lhs.JointID == rhs.JointID &&
    lhs.TargetValue == rhs.TargetValue;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::actuatorcontroller_ros::ActuatorCommand_<ContainerAllocator1> & lhs, const ::actuatorcontroller_ros::ActuatorCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace actuatorcontroller_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::actuatorcontroller_ros::ActuatorCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actuatorcontroller_ros::ActuatorCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actuatorcontroller_ros::ActuatorCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actuatorcontroller_ros::ActuatorCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actuatorcontroller_ros::ActuatorCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actuatorcontroller_ros::ActuatorCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::actuatorcontroller_ros::ActuatorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "95d799a69e6858be0eccbbdb1d8e46e7";
  }

  static const char* value(const ::actuatorcontroller_ros::ActuatorCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x95d799a69e6858beULL;
  static const uint64_t static_value2 = 0x0eccbbdb1d8e46e7ULL;
};

template<class ContainerAllocator>
struct DataType< ::actuatorcontroller_ros::ActuatorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "actuatorcontroller_ros/ActuatorCommand";
  }

  static const char* value(const ::actuatorcontroller_ros::ActuatorCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::actuatorcontroller_ros::ActuatorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 JointID\n"
"float64 TargetValue\n"
;
  }

  static const char* value(const ::actuatorcontroller_ros::ActuatorCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::actuatorcontroller_ros::ActuatorCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.JointID);
      stream.next(m.TargetValue);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActuatorCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::actuatorcontroller_ros::ActuatorCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::actuatorcontroller_ros::ActuatorCommand_<ContainerAllocator>& v)
  {
    s << indent << "JointID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.JointID);
    s << indent << "TargetValue: ";
    Printer<double>::stream(s, indent + "  ", v.TargetValue);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTUATORCONTROLLER_ROS_MESSAGE_ACTUATORCOMMAND_H
