// Generated by gencpp from file actuatorcontroller_ros/AttributeLookup.msg
// DO NOT EDIT!


#ifndef ACTUATORCONTROLLER_ROS_MESSAGE_ATTRIBUTELOOKUP_H
#define ACTUATORCONTROLLER_ROS_MESSAGE_ATTRIBUTELOOKUP_H

#include <ros/service_traits.h>


#include <actuatorcontroller_ros/AttributeLookupRequest.h>
#include <actuatorcontroller_ros/AttributeLookupResponse.h>


namespace actuatorcontroller_ros
{

struct AttributeLookup
{

typedef AttributeLookupRequest Request;
typedef AttributeLookupResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AttributeLookup
} // namespace actuatorcontroller_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::actuatorcontroller_ros::AttributeLookup > {
  static const char* value()
  {
    return "b305ca97b07bb254bb42e700d6815d17";
  }

  static const char* value(const ::actuatorcontroller_ros::AttributeLookup&) { return value(); }
};

template<>
struct DataType< ::actuatorcontroller_ros::AttributeLookup > {
  static const char* value()
  {
    return "actuatorcontroller_ros/AttributeLookup";
  }

  static const char* value(const ::actuatorcontroller_ros::AttributeLookup&) { return value(); }
};


// service_traits::MD5Sum< ::actuatorcontroller_ros::AttributeLookupRequest> should match
// service_traits::MD5Sum< ::actuatorcontroller_ros::AttributeLookup >
template<>
struct MD5Sum< ::actuatorcontroller_ros::AttributeLookupRequest>
{
  static const char* value()
  {
    return MD5Sum< ::actuatorcontroller_ros::AttributeLookup >::value();
  }
  static const char* value(const ::actuatorcontroller_ros::AttributeLookupRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::actuatorcontroller_ros::AttributeLookupRequest> should match
// service_traits::DataType< ::actuatorcontroller_ros::AttributeLookup >
template<>
struct DataType< ::actuatorcontroller_ros::AttributeLookupRequest>
{
  static const char* value()
  {
    return DataType< ::actuatorcontroller_ros::AttributeLookup >::value();
  }
  static const char* value(const ::actuatorcontroller_ros::AttributeLookupRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::actuatorcontroller_ros::AttributeLookupResponse> should match
// service_traits::MD5Sum< ::actuatorcontroller_ros::AttributeLookup >
template<>
struct MD5Sum< ::actuatorcontroller_ros::AttributeLookupResponse>
{
  static const char* value()
  {
    return MD5Sum< ::actuatorcontroller_ros::AttributeLookup >::value();
  }
  static const char* value(const ::actuatorcontroller_ros::AttributeLookupResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::actuatorcontroller_ros::AttributeLookupResponse> should match
// service_traits::DataType< ::actuatorcontroller_ros::AttributeLookup >
template<>
struct DataType< ::actuatorcontroller_ros::AttributeLookupResponse>
{
  static const char* value()
  {
    return DataType< ::actuatorcontroller_ros::AttributeLookup >::value();
  }
  static const char* value(const ::actuatorcontroller_ros::AttributeLookupResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ACTUATORCONTROLLER_ROS_MESSAGE_ATTRIBUTELOOKUP_H
