// Generated by gencpp from file actuatorcontroller_ros/AttributeQuery.msg
// DO NOT EDIT!


#ifndef ACTUATORCONTROLLER_ROS_MESSAGE_ATTRIBUTEQUERY_H
#define ACTUATORCONTROLLER_ROS_MESSAGE_ATTRIBUTEQUERY_H

#include <ros/service_traits.h>


#include <actuatorcontroller_ros/AttributeQueryRequest.h>
#include <actuatorcontroller_ros/AttributeQueryResponse.h>


namespace actuatorcontroller_ros
{

struct AttributeQuery
{

typedef AttributeQueryRequest Request;
typedef AttributeQueryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AttributeQuery
} // namespace actuatorcontroller_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::actuatorcontroller_ros::AttributeQuery > {
  static const char* value()
  {
    return "1811fc90c11724f9bd0bb72df9c9acd3";
  }

  static const char* value(const ::actuatorcontroller_ros::AttributeQuery&) { return value(); }
};

template<>
struct DataType< ::actuatorcontroller_ros::AttributeQuery > {
  static const char* value()
  {
    return "actuatorcontroller_ros/AttributeQuery";
  }

  static const char* value(const ::actuatorcontroller_ros::AttributeQuery&) { return value(); }
};


// service_traits::MD5Sum< ::actuatorcontroller_ros::AttributeQueryRequest> should match
// service_traits::MD5Sum< ::actuatorcontroller_ros::AttributeQuery >
template<>
struct MD5Sum< ::actuatorcontroller_ros::AttributeQueryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::actuatorcontroller_ros::AttributeQuery >::value();
  }
  static const char* value(const ::actuatorcontroller_ros::AttributeQueryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::actuatorcontroller_ros::AttributeQueryRequest> should match
// service_traits::DataType< ::actuatorcontroller_ros::AttributeQuery >
template<>
struct DataType< ::actuatorcontroller_ros::AttributeQueryRequest>
{
  static const char* value()
  {
    return DataType< ::actuatorcontroller_ros::AttributeQuery >::value();
  }
  static const char* value(const ::actuatorcontroller_ros::AttributeQueryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::actuatorcontroller_ros::AttributeQueryResponse> should match
// service_traits::MD5Sum< ::actuatorcontroller_ros::AttributeQuery >
template<>
struct MD5Sum< ::actuatorcontroller_ros::AttributeQueryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::actuatorcontroller_ros::AttributeQuery >::value();
  }
  static const char* value(const ::actuatorcontroller_ros::AttributeQueryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::actuatorcontroller_ros::AttributeQueryResponse> should match
// service_traits::DataType< ::actuatorcontroller_ros::AttributeQuery >
template<>
struct DataType< ::actuatorcontroller_ros::AttributeQueryResponse>
{
  static const char* value()
  {
    return DataType< ::actuatorcontroller_ros::AttributeQuery >::value();
  }
  static const char* value(const ::actuatorcontroller_ros::AttributeQueryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ACTUATORCONTROLLER_ROS_MESSAGE_ATTRIBUTEQUERY_H
