// Generated by gencpp from file actuatorcontroller_ros/AttributeDictionary.msg
// DO NOT EDIT!


#ifndef ACTUATORCONTROLLER_ROS_MESSAGE_ATTRIBUTEDICTIONARY_H
#define ACTUATORCONTROLLER_ROS_MESSAGE_ATTRIBUTEDICTIONARY_H

#include <ros/service_traits.h>


#include <actuatorcontroller_ros/AttributeDictionaryRequest.h>
#include <actuatorcontroller_ros/AttributeDictionaryResponse.h>


namespace actuatorcontroller_ros
{

struct AttributeDictionary
{

typedef AttributeDictionaryRequest Request;
typedef AttributeDictionaryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AttributeDictionary
} // namespace actuatorcontroller_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::actuatorcontroller_ros::AttributeDictionary > {
  static const char* value()
  {
    return "86cb20b614a056db93aedc2debacabe6";
  }

  static const char* value(const ::actuatorcontroller_ros::AttributeDictionary&) { return value(); }
};

template<>
struct DataType< ::actuatorcontroller_ros::AttributeDictionary > {
  static const char* value()
  {
    return "actuatorcontroller_ros/AttributeDictionary";
  }

  static const char* value(const ::actuatorcontroller_ros::AttributeDictionary&) { return value(); }
};


// service_traits::MD5Sum< ::actuatorcontroller_ros::AttributeDictionaryRequest> should match
// service_traits::MD5Sum< ::actuatorcontroller_ros::AttributeDictionary >
template<>
struct MD5Sum< ::actuatorcontroller_ros::AttributeDictionaryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::actuatorcontroller_ros::AttributeDictionary >::value();
  }
  static const char* value(const ::actuatorcontroller_ros::AttributeDictionaryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::actuatorcontroller_ros::AttributeDictionaryRequest> should match
// service_traits::DataType< ::actuatorcontroller_ros::AttributeDictionary >
template<>
struct DataType< ::actuatorcontroller_ros::AttributeDictionaryRequest>
{
  static const char* value()
  {
    return DataType< ::actuatorcontroller_ros::AttributeDictionary >::value();
  }
  static const char* value(const ::actuatorcontroller_ros::AttributeDictionaryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::actuatorcontroller_ros::AttributeDictionaryResponse> should match
// service_traits::MD5Sum< ::actuatorcontroller_ros::AttributeDictionary >
template<>
struct MD5Sum< ::actuatorcontroller_ros::AttributeDictionaryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::actuatorcontroller_ros::AttributeDictionary >::value();
  }
  static const char* value(const ::actuatorcontroller_ros::AttributeDictionaryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::actuatorcontroller_ros::AttributeDictionaryResponse> should match
// service_traits::DataType< ::actuatorcontroller_ros::AttributeDictionary >
template<>
struct DataType< ::actuatorcontroller_ros::AttributeDictionaryResponse>
{
  static const char* value()
  {
    return DataType< ::actuatorcontroller_ros::AttributeDictionary >::value();
  }
  static const char* value(const ::actuatorcontroller_ros::AttributeDictionaryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ACTUATORCONTROLLER_ROS_MESSAGE_ATTRIBUTEDICTIONARY_H
