// Generated by gencpp from file actuatorcontroller_ros/GeneralQueryResponse.msg
// DO NOT EDIT!


#ifndef ACTUATORCONTROLLER_ROS_MESSAGE_GENERALQUERYRESPONSE_H
#define ACTUATORCONTROLLER_ROS_MESSAGE_GENERALQUERYRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace actuatorcontroller_ros
{
template <class ContainerAllocator>
struct GeneralQueryResponse_
{
  typedef GeneralQueryResponse_<ContainerAllocator> Type;

  GeneralQueryResponse_()
    : ActuatorList()
    , ActuatorSwitch()  {
    }
  GeneralQueryResponse_(const ContainerAllocator& _alloc)
    : ActuatorList(_alloc)
    , ActuatorSwitch(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _ActuatorList_type;
  _ActuatorList_type ActuatorList;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _ActuatorSwitch_type;
  _ActuatorSwitch_type ActuatorSwitch;





  typedef boost::shared_ptr< ::actuatorcontroller_ros::GeneralQueryResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::actuatorcontroller_ros::GeneralQueryResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GeneralQueryResponse_

typedef ::actuatorcontroller_ros::GeneralQueryResponse_<std::allocator<void> > GeneralQueryResponse;

typedef boost::shared_ptr< ::actuatorcontroller_ros::GeneralQueryResponse > GeneralQueryResponsePtr;
typedef boost::shared_ptr< ::actuatorcontroller_ros::GeneralQueryResponse const> GeneralQueryResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::actuatorcontroller_ros::GeneralQueryResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::actuatorcontroller_ros::GeneralQueryResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::actuatorcontroller_ros::GeneralQueryResponse_<ContainerAllocator1> & lhs, const ::actuatorcontroller_ros::GeneralQueryResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ActuatorList == rhs.ActuatorList &&
    lhs.ActuatorSwitch == rhs.ActuatorSwitch;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::actuatorcontroller_ros::GeneralQueryResponse_<ContainerAllocator1> & lhs, const ::actuatorcontroller_ros::GeneralQueryResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace actuatorcontroller_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::actuatorcontroller_ros::GeneralQueryResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actuatorcontroller_ros::GeneralQueryResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actuatorcontroller_ros::GeneralQueryResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actuatorcontroller_ros::GeneralQueryResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actuatorcontroller_ros::GeneralQueryResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actuatorcontroller_ros::GeneralQueryResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::actuatorcontroller_ros::GeneralQueryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ec4e3be84053c1627845c079f4a6e32";
  }

  static const char* value(const ::actuatorcontroller_ros::GeneralQueryResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ec4e3be84053c16ULL;
  static const uint64_t static_value2 = 0x27845c079f4a6e32ULL;
};

template<class ContainerAllocator>
struct DataType< ::actuatorcontroller_ros::GeneralQueryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "actuatorcontroller_ros/GeneralQueryResponse";
  }

  static const char* value(const ::actuatorcontroller_ros::GeneralQueryResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::actuatorcontroller_ros::GeneralQueryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] ActuatorList\n"
"int32[] ActuatorSwitch\n"
;
  }

  static const char* value(const ::actuatorcontroller_ros::GeneralQueryResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::actuatorcontroller_ros::GeneralQueryResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ActuatorList);
      stream.next(m.ActuatorSwitch);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GeneralQueryResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::actuatorcontroller_ros::GeneralQueryResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::actuatorcontroller_ros::GeneralQueryResponse_<ContainerAllocator>& v)
  {
    s << indent << "ActuatorList[]" << std::endl;
    for (size_t i = 0; i < v.ActuatorList.size(); ++i)
    {
      s << indent << "  ActuatorList[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.ActuatorList[i]);
    }
    s << indent << "ActuatorSwitch[]" << std::endl;
    for (size_t i = 0; i < v.ActuatorSwitch.size(); ++i)
    {
      s << indent << "  ActuatorSwitch[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.ActuatorSwitch[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTUATORCONTROLLER_ROS_MESSAGE_GENERALQUERYRESPONSE_H
